name: Run Python Script on Schedule

on:
  push:
    paths:
      - "input.md" # 监听 input.md 文件的更改
  workflow_dispatch: # 也可以手动触发工作流

jobs:
  run-python:
    runs-on: ubuntu-latest # 你可以选择其他操作系统，比如 macos-latest, windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2 # 检出仓库代码

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.10" # 你可以设置所需的 Python 版本

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip

      - name: Run Python script
        run: python run_tracker.py --transitive # 这里指定你要运行的 Python 脚本

      - name: Commit and push output.md
        run: |
          git config --global user.name "tian-2024"
          git config --global user.email "sleeptian@hotmail.com"
          git add output.md  
          git commit -m "Update output.md"  
          git push
